# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hWr0amIY4FdRsLTblGrK1iJxJan1cP8j
"""

import pandas as pd
import matplotlib.pyplot as plt

# Dataset URL (public & stable)
url = "https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv"

# Load data
df = pd.read_csv(url)

# Save raw data file for GitHub submission
df.to_csv("co2_emissions_raw.csv", index=False)

# Basic data cleaning
df = df[df["iso_code"].notna()]        # remove aggregates (World, regions)
df = df[df["year"] >= 2010]            # keep recent years
df = df.dropna(subset=["co2"])          # remove missing values

# Visualization: Top 10 CO2 emitters in latest year
latest_year = df["year"].max()
top10 = (
    df[df["year"] == latest_year]
    .sort_values("co2", ascending=False)
    .head(10)
)

plt.figure()
plt.bar(top10["country"], top10["co2"])
plt.xticks(rotation=45, ha="right")
plt.title(f"Top 10 CO₂ Emitting Countries ({latest_year})")
plt.xlabel("Country")
plt.ylabel("CO₂ Emissions (million tonnes)")
plt.tight_layout()
plt.show()